<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="vprybeha-w7" ignored="3" name="Investments" tests="1" failures="1" timestamp="29 Jan 2019 15:57:21 GMT" time="14.32" errors="0">
  <testcase name="Investment_ACH" time="3.591" classname="UnitClassSet.Investment.test_IndividualUS">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at UnitClassSet.Investment.test_IndividualUS.Investment_ACH(test_IndividualUS.java:30)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Investment_ACH -->
  <testcase name="Investment_Bitcoin" time="0.0" classname="UnitClassSet.Investment.test_IndividualUS">
    <ignored/>
  </testcase> <!-- Investment_Bitcoin -->
  <testcase name="Investment_Wire" time="0.0" classname="UnitClassSet.Investment.test_IndividualUS">
    <ignored/>
  </testcase> <!-- Investment_Wire -->
  <testcase name="Investment_Ethereum" time="0.0" classname="UnitClassSet.Investment.test_IndividualUS">
    <ignored/>
  </testcase> <!-- Investment_Ethereum -->
</testsuite> <!-- Investments -->
