<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="3" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Sone tests" duration-ms="12908" started-at="2019-01-29T15:51:46Z" finished-at="2019-01-29T15:51:59Z">
    <groups>
    </groups>
    <test name="Investments" duration-ms="12908" started-at="2019-01-29T15:51:46Z" finished-at="2019-01-29T15:51:59Z">
      <class name="UnitClassSet.Investment.test_IndividualUS">
        <test-method status="PASS" signature="setup()[pri:0, instance:UnitClassSet.Investment.test_IndividualUS@3c74aa0d]" name="setup" is-config="true" duration-ms="8660" started-at="2019-01-29T15:51:47Z" finished-at="2019-01-29T15:51:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="Investment_ACH()[pri:0, instance:UnitClassSet.Investment.test_IndividualUS@3c74aa0d]" name="Investment_ACH" duration-ms="3233" started-at="2019-01-29T15:51:55Z" finished-at="2019-01-29T15:51:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at UnitClassSet.Investment.test_IndividualUS.Investment_ACH(test_IndividualUS.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Investment_ACH -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:UnitClassSet.Investment.test_IndividualUS@3c74aa0d]" name="teardown" is-config="true" duration-ms="784" started-at="2019-01-29T15:51:59Z" finished-at="2019-01-29T15:51:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Investment_ACH status=FAILURE method=test_IndividualUS.Investment_ACH()[pri:0, instance:UnitClassSet.Investment.test_IndividualUS@3c74aa0d] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void UnitClassSet.Investment.test_IndividualUS.Investment_ACH() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- UnitClassSet.Investment.test_IndividualUS -->
    </test> <!-- Investments -->
  </suite> <!-- Sone tests -->
</testng-results>
